### PR TITLE
fix: select correct legacy version (closes #358)

### LINKED ISSUE #358: Legacy file strategy `latest_installed` selects wrong versions
With `.nvmrc` containing `v18` I get the following output:

```
$ export ASDF_NODEJS_LEGACY_FILE_DYNAMIC_STRATEGY=latest_installed
$ asdf list
  14.19.3
  18.16.0
  18.16.1
  18.2.0
 *18.9.0
  19.4.0
```

Expected behavior is to have `18.16.1` selected. The problem is, that `resolve_legacy_version` uses the order returned by a shell glob in `list_installed_versions`. A simple fix with GNU sort 7.0+ (released 2008) installed is to replace:

```
ASDF_NODEJS_SKIP_NODEBUILD_UPDATE=1 list_installed_versions nodejs
```

by:

```
ASDF_NODEJS_SKIP_NODEBUILD_UPDATE=1 list_installed_versions nodejs | sort -V
```

This does also work with at least FreeBSD's sort, but not macOS, but according to asdf docs coreutils are to be installed, so this should work, too.

### PR DESCRIPTION
**Pull request by luzat**

### CODE REVIEW

**Review by rubiin — APPROVED** [review]

File: lib/utils.sh [hunk 1]
```diff
@@ -84,7 +84,7 @@ resolve_legacy_version() {
   case "$strategy" in
   latest_installed)
     _list() {
-      ASDF_NODEJS_SKIP_NODEBUILD_UPDATE=1 list_installed_versions nodejs
+      ASDF_NODEJS_SKIP_NODEBUILD_UPDATE=1 list_installed_versions nodejs | sort -V
```
Comment (Stratus3D) [inline lib/utils.sh:87]: I don't think `sort -V` is available on older versions of MacOS. In asdf we had to do this: https://github.com/asdf-vm/asdf/blob/ccdd47df9b73d0a22235eb06ad4c48eb57360832/lib/commands/command-update.bash#L45-L49

Comment (luzat) [reply lib/utils.sh]: > I don't think `sort -V` is available on older versions of MacOS. In asdf we had to do this: https://github.com/asdf-vm/asdf/blob/ccdd47df9b73d0a22235eb06ad4c48eb57360832/lib/commands/command-update.bash#L45-L49

This could be used instead. I copied `sort_versions` into this PR.

As I already noted in #358, asdf itself [wants coreutils to be installed on macOS](https://asdf-vm.com/guide/getting-started.html#_1-install-dependencies), but I guess that does not include the requirement that GNU `sort` should be first in `$PATH`.

**Review by Stratus3D — APPROVED** [review]

**Comment by augustobmoura** [comment]
Thanks @luzat!
